[versions]
    ignition = "8.3.3"

[libraries]
    ignition-common = { module = "com.inductiveautomation.ignitionsdk:ignition-common", version.ref = "ignition" }
    ignition-gateway-api = { module = "com.inductiveautomation.ignitionsdk:gateway-api", version.ref = "ignition" }
    ignition-designer-api = { module = "com.inductiveautomation.ignitionsdk:designer-api", version.ref = "ignition" }
    ignition-perspective-common = { module = "com.inductiveautomation.ignitionsdk:perspective-common", version.ref = "ignition" }
    ignition-perspective-designer = { module = "com.inductiveautomation.ignitionsdk:perspective-designer", version.ref = "ignition" }
    ignition-perspective-gateway = { module = "com.inductiveautomation.ignitionsdk:perspective-gateway", version.ref = "ignition" }

    google-guava = { module = "com.google.guava:guava", version = "23.3-jre" }
    google-jsr305 = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }
    ia-gson = { module = "com.inductiveautomation.ignition:ia-gson", version = "2.10.1" }
